### ISSUE TITLE
Filter out events in the past

### ISSUE THREAD

**Issue by floli** [rjhorniii/ical2org#13]
My ics export contains a lot of entries in the past. Is it possible to filter out events that are N days in the past, so that are not written to the org file?

That whould make the org file considerably smaller and parsing time with the org mode agenda view has become an issue if all events are included.

**Comment by jpfairbanks** [comment]
The ICS event is represented by this struct

```go

type Event struct {
	start         time.Time
	end           time.Time
	created       time.Time
	modified      time.Time
	stamp         time.Time
	alarmTime     time.Duration
	importedId    string
	DTZID         []string
	status        string
	description   string
	location      string
	geo           *Geo
	summary       string
	rrule         string
	class         string
	id            string
	sequence      int
	attendees     []*Attendee
	organizer     *Attendee
	wholeDayEvent bool
	inCalendar    *Calendar
	alarmCallback func(*Event)
}
```

You could filter events based on `event.start` and `event.end` in the main loop. That seems like a pretty easy filter to write, it would need a command line flag to trigger it.

**Comment by rjhorniii** [comment]
Yes, it would be easy.  I'll think about the proper command line structure.  For a human control command line it makes sense to specify a date, e.g., after=<date>.  For an automatic script it would be better to be an offset, e.g., after=-14d.  The description will need some warnings about the vagaries of generating systems and time zones.   It would be best to avoid putting the date as yesterday.  That might catch some future events due to time zone effects.

I solved the agenda issue a different way.  I had my big ICS archive for the past 5+ years.  I 
 1) generated a huge org file, 
 2) sorted the org file by date
 3) deleted all the newish stuff that I wanted to preserve. (Saving it into an ongoing events.org)
 4) used grep to get all the ORGUIDs, and
 5) put an "old-stuff" at the start of my automaticly updated events.org, with a big properties having all those ORGUIDs in a single ICAL2ORG drawer.

This looks to the agenda processing like a big block of ordinary text and did not slow down the agenda processing.  It screened out all these events from the automatic updating.  Ical2org sees all those duplicate IDs and does not add them to the events.org

I did this because I've noticed occasional mistakes by people scheduling meetings, such as putting in last year in the date.  When they do that I wanted to see it.  

I use append mode to an events.org file and look at the end of the file to see what has shown up.  This is mostly to notice people scheduling stuff more than a week ahead, because I wouldn't notice that in the agenda.  The side effect is that I catch the occasional mistake in scheduling that puts an event in the past.

With appropriate warnings the flag looks easy to do.  Today and tomorrow look busy for me, but sometime this week.

**Comment by rjhorniii** [comment]
I've got a version working.  Any comments on the following


### After option

The after option specifies that only events after a particular time
should be converted.  The variations in calendar software that
generate Ical events, human error, time zones, and summer time can
make this a bit unpredictable.  The effort to use "then/there local
time" also makes it a bit unpredictable.  For example, person in New
Zealand may occasionally receive future events that originate in the
Americas and that appear to be scheduled in the past.  It is a good idea
to keep this cutoff at least a few days in the past.

There are two forms permitted:

`-after -96h` specifies a duration before now, the time the program is
run.  This must be specified in hours and must be negative.

`-after 2017-12-31` specifies the midnight beginning the first day
that will generate events.  This must be in yyyy-mm-dd notation.  If
the intention had been to only get events in 2018, the option should
have been `-after 2018-01-01`.

**Comment by rjhorniii** [comment]
Fixed in https://github.com/rjhorniii/ical2org/commit/5a010be6e3d3a52b3934350defeffd26d54abfeb
